version: "3"

services:
  rs-calc-api:
    build: ./api/flask
    container_name: rs-calc-api
    user: ${USER_ID}:${GROUP_ID}
    restart: always
    expose:
      - 8080

  nginx-reverse-proxy:
    build: ./api/nginx
    container_name: nginx-reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  
  certbot:
    image: certbot/certbot
    volumes:
     - ./data/certbot/conf:/etc/letsencrypt
     - ./data/certbot/www:/var/www/certbot
 
  rs-calc-front-end:
    image: node:18.8.0-alpine
    network_mode: host
    container_name: rs-calc-front-end
    user: ${USER_ID}:${GROUP_ID}
    working_dir: /usr/src/app
    volumes:
      - ./front-end:/usr/src/app
    command: sh -c 'yarn && yarn start'