---
version: "3.1"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    security_opt:
      - label:type:docker_t
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - nginx_html:/usr/share/nginx/html
      - nginx_dhparam:/etc/nginx/dhparam
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_config:/etc/nginx
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true'

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - nginx_certs:/etc/nginx/certs:rw
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme_data:/etc/acme.sh

  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /root/.docker/config.json:/config.json
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=30
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  rs-calc-api:
    image: index.docker.io/djermy/runeprofitforge-api:prod
    container_name: rs-calc-api
    user: ${USER_ID}:${GROUP_ID}
    restart: always
    expose:
      - 8080
    environment:
      LETSENCRYPT_HOST: api.runeprofitforge.com
      VIRTUAL_HOST: api.runeprofitforge.com
      VIRTUAL_PORT: 8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
 
networks:
  default:
    external:
      name: nginx-proxy

volumes:
  nginx_certs:
  nginx_vhost:
  nginx_html:
  nginx_dhparam:
  nginx_config:
  acme_data: