---
name: API Docker Image Build

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

defaults:
  run:
    working-directory: api/flask/

jobs:
  build:
    name: API Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Build Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: api/flask
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/runeprofitforge-api:test